#pragma once

// Compile-time shims for ESPHome API drift (issue #733).
//
// ClimateTraits feature flags (add/has_feature_flags) and select FixedVector
// landed in ESPHome 2025.11.0. ESPHome 2026.5.0 removed the older
// get/set_supports_* ClimateTraits accessors. This header keeps CN105
// buildable on both sides without changing heat-pump runtime defaults.
//
// Cutoff matches hardware_setting_select.cpp (VERSION_CODE 2025.11.0).

#include "esphome/core/macros.h"
#if defined(__has_include)
#if __has_include("esphome/core/version.h")
#include "esphome/core/version.h"
#endif
#endif
#include "esphome/core/helpers.h"
#include "esphome/components/climate/climate_mode.h"
#include "esphome/components/climate/climate_traits.h"

#include <vector>
#include <string>

#ifndef ESPHOME_VERSION_CODE
// Generated by ESPHome; if missing, assume a current tree (feature-flag API).
#define CN105_ESPHOME_HAS_CLIMATE_FEATURE_FLAGS 1
#define CN105_ESPHOME_HAS_FIXED_VECTOR 1
#else
#define CN105_ESPHOME_HAS_CLIMATE_FEATURE_FLAGS \
    (ESPHOME_VERSION_CODE >= VERSION_CODE(2025, 11, 0))
#define CN105_ESPHOME_HAS_FIXED_VECTOR \
    (ESPHOME_VERSION_CODE >= VERSION_CODE(2025, 11, 0))
#endif

namespace esphome {

inline bool cn105_traits_requires_two_point(const climate::ClimateTraits &traits) {
#if CN105_ESPHOME_HAS_CLIMATE_FEATURE_FLAGS
    return traits.has_feature_flags(climate::CLIMATE_REQUIRES_TWO_POINT_TARGET_TEMPERATURE);
#else
    return traits.get_supports_two_point_target_temperature();
#endif
}

inline void cn105_traits_add_current_temp_and_action(climate::ClimateTraits &traits) {
#if CN105_ESPHOME_HAS_CLIMATE_FEATURE_FLAGS
    traits.add_feature_flags(climate::CLIMATE_SUPPORTS_ACTION |
                             climate::CLIMATE_SUPPORTS_CURRENT_TEMPERATURE);
#else
    traits.set_supports_action(true);
    traits.set_supports_current_temperature(true);
#endif
}

template <typename SelectTraitsT>
inline void cn105_set_select_options(SelectTraitsT &select_traits,
                                     const std::vector<std::string> &options) {
#if CN105_ESPHOME_HAS_FIXED_VECTOR
    FixedVector<const char *> fixed_options;
    fixed_options.init(options.size());
    for (const auto &str : options) {
        fixed_options.push_back(str.c_str());
    }
    select_traits.set_options(fixed_options);
#else
    select_traits.set_options(options);
#endif
}

}  // namespace esphome
