# Defaults for wifi, api and OTA connectivity

wifi:
  ssid: !secret iot_ssid
  password: !secret iot_password
  domain: !secret iot_domain
  output_power: 8.5db

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} ESP"
    password: !secret fallback_password

captive_portal:

api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome

# Enable Web server, version 3
web_server:
  port: 80
  version: 3

# Wifi related sensors
sensor:
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 120s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP
    ssid:
      name: SSID