substitutions:
  name: "garage_ac"
  friendly_name: "Garage AC"
  clim_name: Garage AC Climate

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  #name_add_mac_suffix: true
  on_boot:
    priority: 200
    then:
      - delay: 30s
      - switch.turn_off:
          id: eps32_s3_led_switch
  project:
    name: esphome.clim_and_nt_proxy
    version: "24.7.4.1"

debug:
  update_interval: 5s

# Enable logging
logger:
  baud_rate: 0
  level: DEBUG
  logs:
    EVT_SETS : DEBUG
    WIFI : INFO
    MQTT : INFO
    WRITE_SETTINGS : INFO
    SETTINGS : DEBUG
    STATUS : INFO
    CN105Climate: WARN
    CN105: INFO
    climate: WARN
    sensor: WARN
    chkSum : INFO
    WRITE : WARN
    READ : WARN
    ACK : DEBUG
    REMOTE_TEMP : DEBUG
    Header: INFO
    Decoder : INFO
    CONTROL_WANTED_SETTINGS: INFO    
    control: INFO    
    UPDT_ITVL: DEBUG
    CYCLE: DEBUG    
    esp32_ble_tracker: INFO
    esp32_ble_client: INFO
    esp-idf: INFO

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: latest
  flash_size: 8MB

light:
## G35=RGB WS2812C-2020
  - platform: esp32_rmt_led_strip
    name: Led
    id: led
    internal: true
    rgb_order: GRB
    pin: 35
    num_leds: 4
    # RMT 0 channels will be occupied by IR
    rmt_channel: 1
    chipset: ws2812
    restore_mode: ALWAYS_ON  #OFF?


# mqtt, api, ota, wifi, captive, web, time
<<: !include includes/ha-integration-config.yaml

# display button and api status binary_sensor configuration
<<: !include includes/binary-sensor-config.yaml

# cn105 mitsubishi climate config
<<: !include includes/climate-config.yaml
