substitutions:
  name: garage-ac
  friendly_name: Garage AC
  model: MSZ-HM24NA
  remote_temp_sensor: sensor.average_garage_temperature

packages:
  wifi: !include common/wifi.yaml
  sensors: !include common/sensors.yaml
  heatpump-d1pro: !include common/heatpump-xiaoS3.yaml
  fanspeeds: !include common/heatpump-fanspeeds.yaml
  climate: !include common/heatpump-climate.yaml
  intake-sensors: !include common/heatpump-intake-sensors.yaml
  bt-proxy: !include common/bt-proxy.yaml
