substitutions:
  name: "esp32s3"
  friendly_name: ESPHome esp32s3

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    priority: 200 # Priority 200 aligns with the component initialization phase
    then:
      - delay: 3s # Delay for a few sec before proceeding with the rest of the setup
      - logger.log:
          level: INFO
          format: "Power-on stabilization delay of a few seconds completed. Starting CN105 setup."

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended
    #version: 5.4.0
  variant: esp32s3
  flash_size: 8MB

mqtt:
  broker: home-io.local
  username: awox_mesh2mqtt
  password: !secret mqtt_awox_password
  discovery: true

debug:
  update_interval: 5s

# Enable logging
logger:
  hardware_uart: UART0
  level: DEBUG
  logs:
    esp32_ble_client: INFO
    awox: WARN
    awox.connection: WARN
    EVT_SETS: DEBUG
    WIFI: INFO
    MQTT: INFO
    WRITE_SETTINGS: INFO
    SETTINGS: DEBUG
    STATUS: INFO
    CN105_CONN: DEBUG
    CN105Climate: WARN
    CN105: INFO
    climate: INFO
    sensor: WARN
    chkSum: INFO
    WRITE: WARN
    READ: DEBUG
    ACK: INFO
    Header: INFO
    Decoder: INFO
    CONTROL_WANTED_SETTINGS: INFO
    control: INFO
    UPDT_ITVL: DEBUG
    CYCLE: DEBUG
    awox.mesh: WARN
    OPERATING_STATUS: DEBUG
    # Nouveaux tags pour HEAT_COOL / AUTO dual setpoint
    HEAT_COOL: DEBUG # Traces détaillées consigne glissante et mode AUTO/HEAT_COOL
    DUAL_SP: DEBUG # Traces dual setpoint AUTO mode
    TEMP_SENSOR: INFO
    REMOTE_TEMP: DEBUG
    FUNCTIONS: DEBUG
    HardwareSelect: DEBUG

# Enable Home Assistant API
api:
  services:
    - service: reboot
      then:
        - logger.log: "Redémarrage en cours..."
        - lambda: |-
            esp_restart();

    - service: set_remote_temperature
      variables:
        temperature: float
      then:
        - lambda: "id(heatpump_chambres).set_remote_temperature(temperature);"

    - service: use_internal_temperature
      then:
        - lambda: "id(heatpump_chambres).set_remote_temperature(0);"

  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_pwd

wifi:
  use_address: 192.168.8.246
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password2
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "awox-mesh-proxy Hotspot"
    password: !secret ota_pwd

captive_portal:

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time

# this setting is for local component (code is not on github)
external_components:
  #  - source:
  #     type: git
  #     url: https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub
  #     ref: main

  #- source: github://echavet/MitsubishiCN105ESPHome
  #  refresh: 0s
  #- source: github://echavet/MitsubishiCN105ESPHome@v1.3.4

  #- source:
  #  type: git
  #  url: https://github.com/echavet/MitsubishiCN105ESPHome.git

  #ref: 281-logs-show-incorrect-txrx-pin
  #ref: 277-hvacaction-or-state-always-shows-idle
  #ref: 7378202160c45857326adb9437909ec9722b59e4

  #   - source: github://echavet/MitsubishiCN105ESPHome

  - source:
      type: local
      path: ../components

#  - source:
#      type: local
#      path: components

esp32_ble_tracker:
  scan_parameters:
    active: false

# ATC TO EXCLUDE:
# a4c138b313d2
# a4c13885ba54
# a4c138bdf027
# a4c1385ca2c3

# awox_mesh:
#   mesh_name: !secret mesh_name
#   mesh_password: !secret mesh_password
#   allowed_mac_addresses:
#     - A4:C1:38:78:34:95
#     - A4:C1:38:63:0A:13

#   device_info:
#     - product_id: 0x13
#       device_type: RGB
#       name: SmartLIGHT Color Mesh 9
#       model: SMLm_C9
#       manufacturer: AwoX

#     - product_id: 0x25
#       device_type: RGB
#       name: EGLOPanel 30X30
#       model: EPanel_300
#       manufacturer: EGLO

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ${name} ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${name} IP
    ssid:
      name: ${name} SSID
    bssid:
      name: ${name} BSSID

  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

# Sensors with general information.
sensor:
  - platform: homeassistant
    id: ha_temp_couloir_enfants
    entity_id: sensor.temperature_couloir_enfants_temperature
    internal: true
    on_value:
      then:
        - lambda: |-
            id(heatpump_chambres).set_remote_temperature(x);

  - platform: debug
    free:
      name: "Heap Free"

  # Uptime sensor.
  - platform: uptime
    name: ${name} Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${name} WiFi Signal
    update_interval: 60s

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin:
    number: GPIO00
    mode:
      input: false
      output: true
      pullup: true
  rx_pin:
    number: GPIO04
    mode:
      input: true
      output: false
      pullup: true
      
climate:

  - platform: cn105
    name: Climatisation Chambres
    id: "heatpump_chambres"
    uart_id: HP_UART
    installer_mode: false
    #fahrenheit_compatibility: "true"
    #cn105_mqtt_mim:
    #  mim_trace_topic : "mitsubishi/mim"
    #  mim_forward_buffer_size: 256
    night_mode_switch:
      name: "Night mode"

    compressor_frequency_sensor:
      name: Compressor frequency (clim Chambres)
    outside_air_temperature_sensor:
      name: ${name} Outside air temperature
    vertical_vane_select:
      name: Vane Verticale (chambres)
    #horizontal_vane_select:
    #  name: Vane Horizontale (chambres)
    sub_mode_sensor:
      name: submode sensor
    stage_sensor:
      name: stage sensor
      use_as_operating_fallback: false
    connection_bootstrap_delay: 12s
    remote_temperature_timeout: 90min
    update_interval: 4s # shouldn't be less than 1 second
    debounce_delay: 150ms # delay to prevent bouncing
    supports:
      dual_setpoint: true
      mode: [COOL, HEAT, FAN_ONLY, DRY, AUTO, HEAT_COOL]
      fan_mode: [AUTO, QUIET, LOW, MEDIUM, HIGH]
      swing_mode: ["OFF", VERTICAL]
    visual:
      min_temperature: 17
      max_temperature: 28
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1

    hardware_settings:
      # L'intervalle de lecture des paramètres (Défaut 24h si omis)
      #update_interval: 48h
      update_interval: 14min
      # La liste des paramètres à exposer
      list:
        - code: 102
          name: "Choix Sonde Température"
          options:
            1: "Interne"
            2: "Télécommande"
            3: "Externe (ESPHome)"

        - code: 101
          name: "Redémarrage Auto"
          options:
            1: "Oui"
            2: "Non"
