substitutions:
  name: "atom-s3"
  friendly_name: "M5Stack Atom S3 bt proxy + cn105"
  clim_name: Clim Sejour

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.10.3
  #name_add_mac_suffix: true
  project:
    name: esphome.clim_and_nt_proxy
    version: "25.10.1.0"
  
  # on_boot:
  #   - priority: 1001
  #     then:
  #       - lambda: |-
  #           gpio_reset_pin((gpio_num_t)01);
  #           gpio_reset_pin((gpio_num_t)02);    

esp32:
  board: esp32-s3-devkitc-1

  #board: m5stack-cores3
  #variant: ESP32S3
  framework:
    #type: arduino
    type: esp-idf
    version: recommended
    #version: 5.4.0
  flash_size: 8MB



debug:
  update_interval: 5s

# Enable logging
logger:
  #hardware_uart: USB_CDC
  baud_rate: 0
  level: DEBUG
  logs:
    EVT_SETS : DEBUG
    WIFI : INFO
    MQTT : INFO
    WRITE_SETTINGS : INFO
    SETTINGS : DEBUG
    STATUS : INFO
    CN105Climate: WARN
    CN105: INFO
    climate: INFO
    sensor: WARN
    chkSum : INFO
    WRITE : WARN
    READ : WARN
    ACK : INFO
    REMOTE_TEMP : DEBUG
    Header: INFO
    Decoder : INFO
    CONTROL_WANTED_SETTINGS: INFO    
    control: INFO    
    UPDT_ITVL: DEBUG
    CYCLE: WARN    
    esp32_ble_tracker: INFO
    esp32_ble_client: INFO
    esp-idf: INFO
    OPERATING_STATUS: DEBUG
    # Nouveaux tags pour HEAT_COOL / AUTO dual setpoint
    HEAT_COOL: DEBUG  # Traces détaillées consigne glissante et mode AUTO/HEAT_COOL
    DUAL_SP: DEBUG    # Traces dual setpoint AUTO mode
    TEMP_SENSOR: INFO
    UARTFix: WARN

# mqtt, api, ota, wifi, captive, web, time
<<: !include includes/ha-integration-config.yaml

# display button and api status binary_sensor configuration
<<: !include includes/binary-sensor-config.yaml

# displays infos on atom screen
<<: !include includes/display_config.yaml
# configure esp bluetooth proxy
<<: !include includes/bt-proxy-config.yaml

# cn105 mitsubishi climate config
<<: !include includes/climate-config.yaml
