substitutions:
  name: hvac_name
  friendly_name: HVAC Name
  remote_temp_sensor: sensor.my_room_temperature # Homeassistant sensor providing remote temperature
  api_encryption_key: !secret hvac_api
  ota_esphome_password: !secret hvac_ota

packages:
  #hvac_base: github://echavet/MitsubishiCN105ESPHome/esphome/packages/hvac-base.yaml
  hvac_base: !include packages/hvac-base.yaml
  #hvac-board-d1mini: github://echavet/MitsubishiCN105ESPHome/esphome/packages/hvac-board-d1mini.yaml
  hvac-board-d1mini: !include packages/hvac-board-d1mini.yaml
  #hvac-cn105: github://echavet/MitsubishiCN105ESPHome/esphome/packages/hvac-cn105.yaml
  hvac-cn105: !include packages/hvac-cn105.yaml
  #hvac-remote-temp: github://echavet/MitsubishiCN105ESPHome/esphome/packages/hvac-remote-temp.yaml
  hvac-remote-temp: !include packages/hvac-remote-temp.yaml
  #hvac-auto-dry: github://echavet/MitsubishiCN105ESPHome/esphome/packages/hvac-auto-dry.yaml
  hvac-auto-dry: !include packages/hvac-auto-dry.yaml

debug:

# Enable logging
logger: